services:
    rubencm.storage_flysystem.listener:
        class: rubencm\storage_flysystem\event\listener
        arguments:
            - '@config'
            - '@language'
            - '@storage.attachment'
            - '@storage.avatar'
        tags:
            - { name: event.listener }

# Adapters
    storage.adapter.aws_s3:
        class: rubencm\storage_flysystem\adapter\aws_s3
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.azure_blob:
        class: rubencm\storage_flysystem\adapter\azure_blob
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.dropbox:
        class: rubencm\storage_flysystem\adapter\dropbox
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.google_drive:
        class: rubencm\storage_flysystem\adapter\google_drive
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.ftp:
        class: rubencm\storage_flysystem\adapter\ftp
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

# Providers
    storage.provider.aws_s3:
        class: rubencm\storage_flysystem\provider\aws_s3
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.azure_blob:
        class: rubencm\storage_flysystem\provider\azure_blob
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.dropbox:
        class: rubencm\storage_flysystem\provider\dropbox
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.google_drive:
        class: rubencm\storage_flysystem\provider\google_drive
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.ftp:
        class: rubencm\storage_flysystem\provider\ftp
        arguments:
        tags:
            - { name: storage.provider }
